Add statefulset basic ops for test helper
openstack-k8s-operators/lib-common pull request #131
Opened 2023-01-04 15:02 UTC by bogdando

Signed-off-by: Bohdan Dobrelia <bdobreli@redhat.com>

2023-01-04 15:54 UTC, bogdando commented on modules/test/helpers/conditions.go
> +func (f conditionGetterFunc) GetConditions(name types.NamespacedName) condition.Conditions {
There are still *unused* problems with those. Quite a few operators copy and paste these. Let's figure out how to properly plug that into the test helper

2023-01-04 16:00 UTC, bogdando commented
this is currently needed in order to align nova and placement tests, but other operators can benefit too

2023-01-05 14:31 UTC, bogdando commented on modules/test/helpers/conditions.go
> +func (f conditionGetterFunc) GetConditions(name types.NamespacedName) condition.Conditions {
I'm a bit lost with adapting those as proper interfaces after moved from nova tests

2023-01-05 16:48 UTC, bogdando commented on modules/test/helpers/common.go
> +func (f ConditionGetterFunc) GetConditions(name types.NamespacedName) condition.Conditions {
with this, nova tests refactored can pass.
I cen see other operators use GetConditions() quite extensively, I believe this should help with testing expected conditions there as well

2023-01-06 17:07 UTC, gibizer requested changes
just two small nit but otherwise looks good

2023-01-06 17:07 UTC, gibizer commented on modules/test/helpers/conditions.go
> +}
No newline at the end of the file. Interesting that it is not caught by go fmt or other lint

2023-01-10 11:02 UTC, gibizer approved these changes
/lgtm

2023-01-10 11:02 UTC, merged