Run go work sync during make gowork
openstack-k8s-operators/lib-common pull request #174
Opened 2023-02-16 12:43 UTC by gibizer

This will ensure that the go.mod files in the different modules will not have different versions from the same dependency. Such divergence known to cause troubles when generating manifests in different environments and while lib-common does not provide any CRDs we might have some common structs here in the future.

2023-02-17 17:08 UTC, fao89 approved these changes

2023-02-27 13:55 UTC, bogdando requested changes

2023-02-27 13:55 UTC, bogdando commented on modules/archive/go.mod
> -go 1.19
this doesn't look expected

2023-02-27 13:56 UTC, bogdando commented on modules/storage/go.mod
> -go 1.19
ditto

2023-03-14 07:47 UTC, stuggi approved these changes
/lgtm

2023-03-14 07:48 UTC, merged